// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuuymcVQV7NVYHSVeWzzKwFXw2vczYVBA',
    appId: '1:870025272677:web:cf9cb6f64227260963558c',
    messagingSenderId: '870025272677',
    projectId: 'kano-a26a8',
    authDomain: 'kano-a26a8.firebaseapp.com',
    storageBucket: 'kano-a26a8.firebasestorage.app',
    measurementId: 'G-Z0L0ZFE8MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO63Dv5U2WXaZmmYlHgmGwAcEgVa2GV0M',
    appId: '1:870025272677:android:8d0e622d687459e463558c',
    messagingSenderId: '870025272677',
    projectId: 'kano-a26a8',
    storageBucket: 'kano-a26a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53A0BBtODbiETw3FHoyv7jJNHkS7nfU4',
    appId: '1:870025272677:ios:dc5fe84d94c8a91063558c',
    messagingSenderId: '870025272677',
    projectId: 'kano-a26a8',
    storageBucket: 'kano-a26a8.firebasestorage.app',
    iosBundleId: 'com.example.kanoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB53A0BBtODbiETw3FHoyv7jJNHkS7nfU4',
    appId: '1:870025272677:ios:dc5fe84d94c8a91063558c',
    messagingSenderId: '870025272677',
    projectId: 'kano-a26a8',
    storageBucket: 'kano-a26a8.firebasestorage.app',
    iosBundleId: 'com.example.kanoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuuymcVQV7NVYHSVeWzzKwFXw2vczYVBA',
    appId: '1:870025272677:web:383a6d5fb7c596dc63558c',
    messagingSenderId: '870025272677',
    projectId: 'kano-a26a8',
    authDomain: 'kano-a26a8.firebaseapp.com',
    storageBucket: 'kano-a26a8.firebasestorage.app',
    measurementId: 'G-LDBZ2PS6KF',
  );
}
